package cucumber;

import java.util.ArrayList;
import java.util.List;

import io.cucumber.java.Scenario;
import managers.WebDriverFactory;

public class TestContext {
	private WebDriverFactory webDriverFactory;
	private Scenario scenario;
	private String loggedInUserName;
	private List<String> strCardNames = new ArrayList<String>();
	private List<String> strFieldLables = new ArrayList<String>();
	private List<String> strFieldValues = new ArrayList<String>();
	private List<String> strRecordNumber = new ArrayList<String>();
	public String[][] TestData;
	public boolean isItExpress = true;

	public void addAutogeneratedValues(String cardName, String fieldLabel, String fieldValue,
			String xlRecordNum, TestContext context) {
		strCardNames.add(cardName);
		strFieldLables.add(fieldLabel);
		strFieldValues.add(fieldValue);
		strRecordNumber.add(xlRecordNum);
		context.getScenario().log("Autogenerated Value added Card Name: " + cardName + " Field: " + fieldLabel + " Field Value: "
				+ fieldValue);
	}
	
	public String retrieveAutogeneratedValues(String cardName, String fieldLabel, String recordNum) {
		for (int i = 0; i < strCardNames.size(); i++) {
			if (strCardNames.get(i).equals(cardName)) {
				if (strFieldLables.get(i).equals(fieldLabel)) {
					if (strRecordNumber.get(i).equals(recordNum)) {
						return strFieldValues.get(i);
					}
				}
			}
		}
		return null;
	}
	
	public TestContext() {
		webDriverFactory = new WebDriverFactory();
	}

	public WebDriverFactory getWebDriverManager() {
		return webDriverFactory;
	}

	public Scenario getScenario() {
		return scenario;
	}

	public void setScenario(Scenario scenario) {
		this.scenario = scenario;
	}

	public String getLoggedInUserName() {
		return loggedInUserName;
	}

	public void setLoggedInUserName(String loggedInUserName) {
		this.loggedInUserName = loggedInUserName;
	}


}
